### ISSUE TITLE
Bug: Unable to fetch 

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos4q1a#3]
FileNotFoundError during fetch because of renaming checkpoints dir to databses since we are not actually using any model checkpoints here. 
Exact log:
```
Traceback (most recent call last):
  File "pack.py", line 14, in <module>
    service.save()
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/site-packages/bentoml/service/__init__.py", line 700, in save
    return yc.repository.upload(self, version, labels)
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/site-packages/bentoml/yatai/client/bento_repository_api.py", line 132, in upload
    save_to_dir(bento_service, tmpdir, version, silent=True)
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/site-packages/bentoml/saved_bundle/bundler.py", line 228, in save_to_dir
    _write_bento_content_to_dir(bento_service, path)
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/site-packages/bentoml/saved_bundle/bundler.py", line 91, in _write_bento_content_to_dir
    bento_service.artifacts.save(module_base_path)
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 258, in save
    artifact.save(save_path)
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 181, in wrapped_save
    return original(*args, **kwargs)
  File "/home/dee/eos/dest/eos4q1a/src/service.py", line 145, in save
    self._copy_checkpoints(dst)
  File "/home/dee/eos/dest/eos4q1a/src/service.py", line 114, in _copy_checkpoints
    shutil.copytree(src_folder, dst_folder)
  File "/home/dee/miniconda3/envs/eos4q1a/lib/python3.7/shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dee/eos/dest/eos4q1a/model/checkpoints'
```

Straightforward fix  involving changing `checkpoints_dir` to `databases_dir` in `service.py` and `pack.py`

**Comment by DhanshreeA** [comment]
After fix from #4 
![Screenshot from 2022-12-21 18-47-07](https://user-images.githubusercontent.com/7213136/208914354-b86161a6-69d8-4cb9-9511-4253dd55d9d8.png)
